language: php
php:
  - 5.4
  - 5.5
  - hhvm
services:
  - mysql
  - mongodb
  - memcached
before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add tests/config.ini; fi;'
  - composer install
  - composer require doctrine/orm 2.4.*@dev
  - mysql -e 'create database psx;'
  - mysql -u root psx < tests/psx.sql
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear channel-discover pear.phpunit.de; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install phpunit/DbUnit; fi;'
  - sh -c '( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -S 127.0.0.1:8000 tests/PSX/Http/Server.php; fi; ) &'
  - sleep 4
env:
  - DB=mysql