language: php
php:
  - "5.4"
  - "5.5"
services: 
  - mysql
  - mongodb
  - memcached
before_script:
  - phpenv config-add tests/config.ini
  - composer install
  - composer require doctrine/orm 2.4.*@dev
  - mysql -e 'create database psx;'
  - mysql -u root psx < tests/psx.sql
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/DbUnit
env:
  - DB=mysql