language: php
php:
  - 5.4
  - 5.5
  - hhvm
services:
  - mysql
  - mongodb
  - memcached
matrix:
  allow_failures:
    - php: hhvm
before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add tests/config.ini; fi;'
  - composer install
  - composer require doctrine/orm 2.4.*@dev
  - mysql -e 'create database psx;'
  - mysql -u root psx < tests/psx.sql
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/DbUnit
  - php -S 127.0.0.1:8000 tests/PSX/Http/Server.php &
  - sleep 4
env:
  - DB=mysql