language: php
php:
  - "5.3"
  - "5.4"
before_script:
  - mysql -e 'create database psx;'
  - mysql -u root psx < tests/psx.sql
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/DbUnit
env:
  - DB=mysql