language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
services:
  - mysql
  - mongodb
  - memcached
before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add tests/config.ini; fi;'
  - composer install
  - composer require doctrine/orm ~2.4
  - composer require twig/twig ~1.16
  - mysql -e 'create database psx;'
  - mysql -u root psx < tests/psx.sql
  - sh -c '( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -S 127.0.0.1:8000 tests/PSX/Http/Server.php; fi; ) &'
  - sleep 4
script:
  - vendor/bin/phpunit
env:
  - DB=mysql
